version: 0.2

phases:

  initial:
    commands:
      - sudo apt update
      - curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
      - sudo apt -y install nodejs
      - node  -v 

  pre_build: 
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build