version: 0.2

phases:

  initial:
    commands:
    
  pre_build: 
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build